"""
Django settings for manager_repuestos project.

Generated by 'django-admin startproject' using Django 5.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import environ
import os
from pathlib import Path

#App version
APP_VERSION = "1.0.0"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
#   ENVIRONMENT VARIABLES
# ==============================
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))   # lee .env si existe

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# ==============================
#   SECURITY / KEYS
# ==============================
SECRET_KEY = env("SECRET_KEY")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',
    # apps del sistema
    'core',
    'usuarios',
    #'pedidos',
    'repuestos',
    'stock',
    'facturacion',
    'logistica',
    'reportes',
    'sesiones',
    'clientes',
    'pedidos.apps.PedidosConfig',
    'axes',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "manager_repuestos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "manager_repuestos.context_processors.app_version",
            ],
        },
    },
]

WSGI_APPLICATION = "manager_repuestos.wsgi.application"

#==============================
#   USUARIO CUSTOM
# =============================
AUTH_USER_MODEL = "usuarios.Usuario"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ==============================
#   DATABASES (4 BASES)
# ==============================
DATABASES = {
    # BD principal
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_MAIN_NAME"),
        "USER": env("DB_MAIN_USER"),
        "PASSWORD": env("DB_MAIN_PASS"),
        "HOST": env("DB_MAIN_HOST", default="localhost"),
        "PORT": env("DB_MAIN_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    },

    # Legacy rpg2
    "rpg2": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_RPG2_NAME"),
        "USER": env("DB_RPG2_USER"),
        "PASSWORD": env("DB_RPG2_PASS"),
        "HOST": env("DB_RPG2_HOST", default="localhost"),
        "PORT": env("DB_RPG2_PORT", default="3306"),
        "OPTIONS": {"charset": "latin1"},
    },

    # Legacy clientes
    "cliente": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_CLI_NAME"),
        "USER": env("DB_CLI_USER"),
        "PASSWORD": env("DB_CLI_PASS"),
        "HOST": env("DB_CLI_HOST", default="localhost"),
        "PORT": env("DB_CLI_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb3"},
    },

    # BD remota (mismo servidor)
    "remota": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_REM_NAME"),
        "USER": env("DB_REM_USER"),
        "PASSWORD": env("DB_REM_PASS"),
        "HOST": env("DB_REM_HOST", default="localhost"),
        "PORT": env("DB_REM_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    },
}



# Password validation"no-reply@localhost"
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_I18N = True
USE_TZ = True






# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Direccionamiento automatico
LOGIN_URL = 'sesiones:login'
LOGIN_REDIRECT_URL = '/pedidos/listar/'
LOGOUT_REDIRECT_URL = 'sesiones:login'



#Extension de la garantia[meses]
GARANTIA_MESES = 36

# Email real — puedes usar SMTP de tu empresa o Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD= env("EMAIL_HOST_PASSWORD")

# URL
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")


# ============================================================
# DATOS DE EMPRESA
# ============================================================

EMPRESA_NOMBRE = "CEC Electrónica SRL"
EMPRESA_DIRECCION = ("Bv. Los Hungaros 5027 5147 Los Boulevares Córdoba - Argentina")
EMPRESA_CUIT = "33-56350432-9"
EMPRESA_INGRESOS_BRUTOS = "9042314732"
EMPRESA_INICIO_ACTIVIDADES = "23/08/1977"
EMPRESA_LOGO = BASE_DIR / "static" / "images" / "favicon.png"

# ============================================================
# LIMITES PAGINADORES
# ============================================================
PAGINACION_PC = 25
PAGINACION_MOVIL = 10


AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

