"""
Django settings for manager_repuestos project.

Generated by 'django-admin startproject' using Django 5.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import environ
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
#   ENVIRONMENT VARIABLES
# ==============================
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))   # lee .env si existe

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# ==============================
#   SECURITY / KEYS
# ==============================
SECRET_KEY = env("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS",default=['localhost', '127.0.0.1'])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',
    # apps del sistema
    'core',
    'usuarios',
    'pedidos',
    'repuestos',
    'stock',
    'facturacion',
    'logistica',
    'reportes',
    'sesiones',
    'clientes',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "manager_repuestos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "manager_repuestos.wsgi.application"

#==============================
#   USUARIO CUSTOM
# =============================
AUTH_USER_MODEL = "usuarios.Usuario"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ==============================
#   DATABASES (4 BASES)
# ==============================
DATABASES = {
    # BD principal
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_MAIN_NAME"),
        "USER": env("DB_MAIN_USER"),
        "PASSWORD": env("DB_MAIN_PASS"),
        "HOST": env("DB_MAIN_HOST", default="localhost"),
        "PORT": env("DB_MAIN_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    },

    # Legacy rpg2
    "rpg2": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_RPG2_NAME"),
        "USER": env("DB_RPG2_USER"),
        "PASSWORD": env("DB_RPG2_PASS"),
        "HOST": env("DB_RPG2_HOST", default="localhost"),
        "PORT": env("DB_RPG2_PORT", default="3306"),
        "OPTIONS": {"charset": "latin1"},
    },

    # Legacy clientes
    "cliente": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_CLI_NAME"),
        "USER": env("DB_CLI_USER"),
        "PASSWORD": env("DB_CLI_PASS"),
        "HOST": env("DB_CLI_HOST", default="localhost"),
        "PORT": env("DB_CLI_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb3"},
    },

    # BD remota (mismo servidor)
    "remota": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_REM_NAME"),
        "USER": env("DB_REM_USER"),
        "PASSWORD": env("DB_REM_PASS"),
        "HOST": env("DB_REM_HOST", default="localhost"),
        "PORT": env("DB_REM_PORT", default="3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_I18N = True
USE_TZ = True






# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Direccionamiento automatico
LOGIN_URL = '/session/login/'
LOGIN_REDIRECT_URL = '/'        # a dónde va luego de loguearse
LOGOUT_REDIRECT_URL = '/sesion/login/' # a dónde va luego de desloguearse

#Extension de la garantia[meses]
GARANTIA_MESES = 36