"""
Django settings for manager_repuestos project.

Generated by 'django-admin startproject' using Django 5.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2bqln7rwo1#w5*rf#n#9jm_9w=*&q5+er8p^#id5&l_66of2bs"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.100.20',   # IP LAN de tu servidor
    '192.168.1.50',
    '*'                # (opcional durante desarrollo)]
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django-extensions
    'django_extensions',
    # apps del sistema
    'core',
    'usuarios',
    'pedidos',
    'repuestos',
    'stock',
    'facturacion',
    'logistica',
    'reportes',
    'sesiones',
    'clientes',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "manager_repuestos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "manager_repuestos.wsgi.application"

AUTH_USER_MODEL = "usuarios.Usuario"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # ==============================
    # Base principal del proyecto
    # ==============================
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'manager_repuestos',
        'USER': 'root',
        'PASSWORD': 'Tvq114-e112906',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },

    # ==============================
    # BD legacy rpg2
    # (Seguimiento)
    # ==============================
    'rpg2': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rpg2',
        'USER': 'root',
        'PASSWORD': 'Tvq114-e112906',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'latin1',       # lo habitual en sistemas viejos
        }
    },

    # ==============================
    # BD legacy clientes
    # (datos)
    # ==============================
    'cliente': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cliente',
        'USER': 'root',
        'PASSWORD': 'Tvq114-e112906',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb3',
        }
    },

    # ==============================
    # BD remota (pero en el MISMO servidor, jaja)
    # (material, material2, grupos, equipos, listamat, etc.)
    # ==============================
    'remota': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'remota',       # ESTA ES LA BASE REMOTA
        'USER': 'root',
        'PASSWORD': 'Tvq114-e112906',
        'HOST': 'localhost',     # MISMO servidor
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_TZ = True

USE_I18N = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Direccionamiento automatico
LOGIN_URL = '/session/login/'
LOGIN_REDIRECT_URL = '/'        # a dónde va luego de loguearse
LOGOUT_REDIRECT_URL = '/sesion/login/' # a dónde va luego de desloguearse

#Extension de la garantia[meses]
GARANTIA_MESES = 36