# Generated by Django 5.1.14 on 2025-11-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_repuesto", models.IntegerField()),
                ("cantidad", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CREADO", "Creado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("FACTURADO", "Facturado"),
                            ("PAGADO", "Pagado"),
                            ("PREPARANDO", "Preparando"),
                            ("CONSOLIDADO", "Consolidado"),
                            ("ENVIADO", "Enviado"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="CREADO",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
        ),
    ]
