# Generated by Django 5.1.14 on 2025-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_repuesto", models.IntegerField()),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cod_cliente", models.IntegerField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CREADO", "Creado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CERRADO", "Cerrado"),
                            ("FACTURADO", "Facturado"),
                            ("PAGADO", "Pagado"),
                            ("PREPARANDO", "Preparando"),
                            ("CONSOLIDADO", "Consolidado"),
                            ("ENVIADO", "Enviado"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
        ),
    ]
