# Generated by Django 5.1.15 on 2026-01-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_detallepedido_numero_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallepedido",
            name="numero_serie",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
