# Generated by Django 5.2.11 on 2026-02-16 19:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_alter_detallepedido_numero_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallepedido",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal(
                            "0.001000000000000000020816681711721685132943093776702880859375"
                        )
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="detallepedido",
            constraint=models.UniqueConstraint(
                fields=("cod_pedido", "cod_repuesto"), name="unique_repuesto_por_pedido"
            ),
        ),
    ]
