# Generated by Django 5.2.12 on 2026-03-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_historialestadopedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepedido",
            name="preparado",
            field=models.BooleanField(default=False),
        ),
    ]
