# Generated by Django 5.2.12 on 2026-03-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_detallepedido_preparado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallepedido",
            name="preparado",
        ),
        migrations.AddField(
            model_name="detallepedido",
            name="cantidad_preparada",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
