# Generated by Django 5.2.12 on 2026-03-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_remove_detallepedido_preparado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fecha_envio",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
