# Generated by Django 5.2.12 on 2026-03-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_pedido_fecha_envio"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fecha_entrega",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
