# Generated by Django 5.2.13 on 2026-05-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_pedido_fecha_entrega"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialestadopedido",
            name="pedido_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pedidos.pedido",
            ),
        ),
    ]
