# Generated by Django 5.1.14 on 2025-11-16 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "equipo",
                    models.CharField(
                        blank=True, db_column="equipo", max_length=150, null=True
                    ),
                ),
                (
                    "id_equi",
                    models.AutoField(
                        db_column="id_equi", primary_key=True, serialize=False
                    ),
                ),
                ("notas", models.TextField(db_column="notas")),
                (
                    "id_grup",
                    models.IntegerField(blank=True, db_column="id_grup", null=True),
                ),
                (
                    "obsoleto",
                    models.IntegerField(blank=True, db_column="obsoleto", null=True),
                ),
            ],
            options={
                "db_table": "equipos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grupos",
            fields=[
                (
                    "GRUPO",
                    models.CharField(
                        blank=True, db_column="GRUPO", max_length=50, null=True
                    ),
                ),
                (
                    "id_grup",
                    models.AutoField(
                        db_column="id_grup", primary_key=True, serialize=False
                    ),
                ),
                ("notas", models.TextField(blank=True, db_column="notas", null=True)),
                ("grupo_conjuntos", models.IntegerField(db_column="grupo_conjuntos")),
                ("grupo_embalaje", models.IntegerField(db_column="grupo_embalaje")),
                ("relevanciaMadre", models.IntegerField(db_column="relevanciaMadre")),
            ],
            options={
                "db_table": "grupos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Listamat",
            fields=[
                (
                    "id_listamat",
                    models.AutoField(
                        db_column="id_listamat", primary_key=True, serialize=False
                    ),
                ),
                (
                    "id_mate",
                    models.IntegerField(blank=True, db_column="id_mate", null=True),
                ),
                ("critico", models.IntegerField(db_column="critico")),
                (
                    "id_equi",
                    models.IntegerField(blank=True, db_column="id_equi", null=True),
                ),
                ("observa", models.CharField(db_column="observa", max_length=50)),
                (
                    "cantidad",
                    models.FloatField(blank=True, db_column="cantidad", null=True),
                ),
                ("imprimir", models.SmallIntegerField(db_column="imprimir")),
            ],
            options={
                "db_table": "listamat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("unidad", models.CharField(db_column="unidad", max_length=25)),
                ("fecha_precio", models.IntegerField(db_column="fecha_precio")),
                ("comprar", models.IntegerField(db_column="comprar")),
                (
                    "stock",
                    models.DecimalField(
                        db_column="stock", decimal_places=3, max_digits=11
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        db_column="precio", decimal_places=3, max_digits=11
                    ),
                ),
                (
                    "id_mate",
                    models.AutoField(
                        db_column="id_mate", primary_key=True, serialize=False
                    ),
                ),
                ("critico", models.IntegerField(db_column="critico")),
                ("pila", models.IntegerField(db_column="pila")),
                ("valor", models.CharField(db_column="valor", max_length=50)),
                ("lugar", models.CharField(db_column="lugar", max_length=50)),
                ("origen", models.SmallIntegerField(db_column="origen")),
                ("historia", models.TextField(db_column="historia")),
                ("div_precio", models.IntegerField(db_column="div_precio")),
                ("descripcio", models.TextField(db_column="descripcio")),
                (
                    "stockNC",
                    models.DecimalField(
                        db_column="stockNC", decimal_places=3, max_digits=11
                    ),
                ),
                (
                    "stockProd",
                    models.DecimalField(
                        db_column="stockProd", decimal_places=3, max_digits=11
                    ),
                ),
                ("grafLink", models.CharField(db_column="grafLink", max_length=250)),
                (
                    "cod_tipo_producto",
                    models.IntegerField(db_column="cod_tipo_producto"),
                ),
                ("cod_M2", models.IntegerField(db_column="cod_M2")),
            ],
            options={
                "db_table": "material",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "seg_codigo",
                    models.BigAutoField(
                        db_column="SEG_CODIGO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "seg_numero_serie",
                    models.CharField(
                        blank=True,
                        db_column="SEG_NUMERO_SERIE",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "seg_fecha_liberacion",
                    models.DateTimeField(
                        blank=True, db_column="SEG_FECHA_LIBERACION", null=True
                    ),
                ),
                (
                    "equi_codigo",
                    models.BigIntegerField(
                        blank=True, db_column="EQUI_CODIGO", null=True
                    ),
                ),
            ],
            options={
                "db_table": "seguimiento",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Material2",
            fields=[
                (
                    "material",
                    models.OneToOneField(
                        db_column="id_mate",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="repuestos.material",
                    ),
                ),
                ("moneda", models.IntegerField(db_column="moneda")),
                (
                    "consumo",
                    models.DecimalField(
                        db_column="consumo", decimal_places=3, max_digits=11
                    ),
                ),
                ("fecha_consumo", models.IntegerField(db_column="fecha_consumo")),
                ("requerimientos", models.TextField(db_column="requerimientos")),
                ("req_especial", models.IntegerField(db_column="req_especial")),
                ("obsoleto", models.IntegerField(db_column="obsoleto")),
                ("discontinuado", models.BooleanField(db_column="discontinuado")),
                ("discont_razon", models.TextField(db_column="discont_razon")),
                ("criticidad", models.TextField(db_column="criticidad")),
                ("datasheet", models.CharField(db_column="datasheet", max_length=100)),
                ("fecha_precio", models.IntegerField(db_column="fecha_precio")),
                ("Demora", models.IntegerField(db_column="Demora")),
                ("reemplazo", models.IntegerField(db_column="reemplazo")),
                ("id_mate_cat", models.SmallIntegerField(db_column="id_mate_cat")),
                ("esimportado", models.BooleanField(db_column="esimportado")),
                ("relevancia", models.IntegerField(db_column="relevancia")),
            ],
            options={
                "db_table": "material2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Repuesto",
            fields=[],
            options={
                "verbose_name": "Repuesto",
                "verbose_name_plural": "Repuestos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("repuestos.material",),
        ),
    ]
