# Generated by Django 5.2.11 on 2026-02-16 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
        ("pedidos", "0006_historialestadopedido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factura",
            options={"ordering": ["-numero"]},
        ),
        migrations.AddField(
            model_name="factura",
            name="factura_referencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_credito",
                to="facturacion.factura",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="numero",
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factura",
            name="tipo",
            field=models.CharField(
                choices=[("FACTURA", "Factura"), ("NOTA_CREDITO", "Nota de Crédito")],
                default="FACTURA",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EMITIDA", "Emitida"),
                    ("PAGADA", "Pagada"),
                    ("ANULADA", "Anulada"),
                ],
                default="BORRADOR",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="pedido",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factura",
                to="pedidos.pedido",
            ),
        ),
        migrations.CreateModel(
            name="HistorialEstadoFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=15)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="facturacion.factura",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
