# Generated by Django 5.2.11 on 2026-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion",
            "0002_alter_factura_options_factura_factura_referencia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="numero",
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
