# Generated by Django 5.2.11 on 2026-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0003_alter_factura_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="cliente",
        ),
        migrations.AddField(
            model_name="factura",
            name="cod_cliente",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
