# Generated by Django 5.2.11 on 2026-02-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_remove_factura_cliente_factura_cod_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="AplicacionCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicaciones_credito",
                        to="facturacion.factura",
                    ),
                ),
                (
                    "nota_credito",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "NOTA_CREDITO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicaciones_realizadas",
                        to="facturacion.factura",
                    ),
                ),
            ],
            options={
                "unique_together": {("factura", "nota_credito")},
            },
        ),
    ]
