# Generated by Django 5.2.11 on 2026-02-26 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_aplicacioncredito"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="consumida",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="factura",
            name="factura_referencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_generadas",
                to="facturacion.factura",
            ),
        ),
        migrations.DeleteModel(
            name="AplicacionCredito",
        ),
    ]
