# Generated by Django 5.2.11 on 2026-02-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion",
            "0006_factura_consumida_alter_factura_factura_referencia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EMITIDA", "Emitida"),
                    ("PAGADA", "Pagada"),
                    ("CONSUMIDA", "Consumida"),
                    ("ANULADA", "Anulada"),
                ],
                default="BORRADOR",
                max_length=15,
            ),
        ),
    ]
