# Generated by Django 5.2.11 on 2026-02-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0007_alter_factura_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="consumida",
        ),
    ]
