# Generated by Django 5.2.13 on 2026-06-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0008_remove_factura_consumida"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="fecha_ultimo_email",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último envío por email"
            ),
        ),
    ]
