# Generated by Django 5.1.14 on 2025-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="calle",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cuit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="localidad",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="pais",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="provincia",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="razon_social",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
