# Generated by Django 5.1.14 on 2025-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_calle_alter_usuario_cuit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="apellido",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="documento",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("CUIT", "CUIT"),
                    ("PAS", "Pasaporte"),
                    ("LE", "Libreta de Enrolamiento"),
                    ("LC", "Libreta Cívica"),
                ],
                default="DNI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("operador", "Operador"),
                    ("despachante", "Despachante"),
                    ("transportista", "Transportista"),
                    ("gerente", "Gerente"),
                    ("admin", "Administrador"),
                ],
                default="operador",
                max_length=20,
            ),
        ),
    ]
