# Generated by Django 5.1.14 on 2025-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logistica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, help_text="Actualización automática del registro"
                    ),
                ),
                (
                    "codigo_seguimiento",
                    models.CharField(
                        blank=True,
                        help_text="Tracking provisto por la empresa de transporte",
                        max_length=100,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
        ),
    ]
