# Generated by Django 5.1.15 on 2026-01-14 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedidos", "0004_alter_detallepedido_numero_serie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_despacho", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PREPARADO", "Preparado"),
                            ("DESPACHADO", "Despachado"),
                            ("ENTREGADO", "Entregado"),
                        ],
                        default="PREPARADO",
                        max_length=15,
                    ),
                ),
                ("tracking", models.CharField(blank=True, max_length=100)),
                ("bultos", models.PositiveIntegerField(default=1)),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envio",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "transportista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envios_transportados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logistica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, help_text="Actualización automática del registro"
                    ),
                ),
                (
                    "codigo_seguimiento",
                    models.CharField(
                        blank=True,
                        help_text="Tracking provisto por la empresa de transporte",
                        max_length=100,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cod_operador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario interno que realizó la última acción",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operaciones_logistica",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cod_pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistica",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "cod_transportista",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transportista asignado al envío",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_transportista",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenPreparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PREPARACION", "En preparación"),
                            ("COMPLETA", "Completa"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envios",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_preparacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreparacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repuesto_id", models.IntegerField()),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENCONTRADO", "Encontrado"),
                            ("FALTANTE", "Faltante"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="logistica.ordenpreparacion",
                    ),
                ),
            ],
        ),
    ]
