# Generated by Django 5.1.14 on 2025-11-20 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistica", "0001_initial"),
        ("pedidos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logistica",
            name="cod_operador",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario interno que realizó la última acción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operaciones_logistica",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="logistica",
            name="cod_pedido",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logistica",
                to="pedidos.pedido",
            ),
        ),
        migrations.AddField(
            model_name="logistica",
            name="cod_transportista",
            field=models.ForeignKey(
                blank=True,
                help_text="Transportista asignado al envío",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios_transportista",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
