# Generated by Django 5.1.14 on 2025-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=100)),
                ("cuit", models.CharField(db_column="cuit", max_length=15)),
                ("domicilio", models.CharField(db_column="domicilio", max_length=50)),
                ("ciudad", models.CharField(db_column="ciudad", max_length=40)),
                ("cod_postal", models.CharField(db_column="cod_postal", max_length=10)),
                ("provincia", models.CharField(db_column="provincia", max_length=20)),
                ("pais", models.CharField(db_column="pais", max_length=20)),
                (
                    "telefono",
                    models.CharField(
                        blank=True, db_column="telefono", max_length=40, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "datos",
                "managed": False,
            },
        ),
    ]
